In [1]:
import pandas as pd
import numpy as num_paths
import matplotlib.pyplot as psnrResault
import seaborn as sns
sns.set(style="whitegrid")
import warnings
warnings.filterwarnings("ignore")

/home/gurhancoban/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
df=pd.read_csv("data05052024.csv")

In [3]:
df=pd.DataFrame(df)
df.head()

,host,psnr,ssim_first,ssim_second,kaynak,kayitboyut,kayip,kayip_orani,type,server
0,h1,36.862369,0.996128,24.120767,67209812,67371008,-161196,-0.239840,1,h10
1,h2,32.694799,0.989303,19.707364,67209812,67108864,100948,0.150198,1,h10
2,h3,26.890008,0.975645,16.134129,67209812,65536000,1673812,2.490428,1,h10
3,h4,26.051045,0.967388,14.866233,67209812,62390272,4819540,7.170887,1,h10
4,h5,25.562017,0.960809,14.068191,67209812,60030976,7178836,10.681232,1,h10

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
psnr,150.0,3.315859e+01,6.380762e+00,2.070984e+01,2.616131e+01,3.573178e+01,3.942195e+01,4.071766e+01
ssim_first,150.0,9.842904e-01,1.980920e-02,8.758290e-01,9.701200e-01,9.954675e-01,9.981587e-01,9.986090e-01
ssim_second,150.0,2.164763e+01,5.772475e+00,9.059810e+00,1.524629e+01,2.343642e+01,2.735068e+01,2.856669e+01
kaynak,150.0,6.720981e+07,0.000000e+00,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,150.0,6.573698e+07,2.816085e+06,5.845811e+07,6.514278e+07,6.737101e+07,6.737101e+07,6.737101e+07
kayip,150.0,1.472835e+06,2.816085e+06,-1.611960e+05,-1.611960e+05,-1.611960e+05,2.067028e+06,8.751700e+06
kayip_orani,150.0,2.191399e+00,4.189991e+00,-2.398400e-01,-2.398400e-01,-2.398400e-01,3.075485e+00,1.302146e+01
type,150.0,2.000000e+00,8.974236e-01,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00

In [5]:
h6_2=df[df["type"]==2]
h6_2=h6_2[df["host"]=="h6"]
h6_1=df[df["type"]==1]
h6_1=h6_1[df["host"]=="h6"]

In [6]:
h6_1.describe().T

,count,mean,std,min,25%,50%,75%,max
psnr,10.0,2.186307e+01,1.742930,2.070984e+01,2.102502e+01,2.109997e+01,2.119793e+01,2.519441e+01
ssim_first,10.0,9.433123e-01,0.009398,9.340840e-01,9.387147e-01,9.399060e-01,9.420855e-01,9.605840e-01
ssim_second,10.0,1.252848e+01,0.814638,1.181012e+01,1.212648e+01,1.221192e+01,1.237219e+01,1.404331e+01
kaynak,10.0,6.720981e+07,0.000000,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,10.0,5.903483e+07,297610.097301,5.845811e+07,5.878579e+07,5.924454e+07,5.924454e+07,5.924454e+07
kayip,10.0,8.174983e+06,297610.097301,7.965268e+06,7.965268e+06,7.965268e+06,8.424020e+06,8.751700e+06
kayip_orani,10.0,1.216338e+01,0.442808,1.185135e+01,1.185135e+01,1.185135e+01,1.253391e+01,1.302146e+01
type,10.0,1.000000e+00,0.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [7]:
h6_2.describe().T

,count,mean,std,min,25%,50%,75%,max
psnr,5.0,3.573736e+01,4.626644,2.951696e+01,3.230746e+01,3.729621e+01,3.978308e+01,3.978308e+01
ssim_first,5.0,9.960784e-01,0.002637,9.922480e-01,9.948640e-01,9.963020e-01,9.984890e-01,9.984890e-01
ssim_second,5.0,2.494698e+01,3.186819,2.110581e+01,2.289364e+01,2.432073e+01,2.820737e+01,2.820737e+01
kaynak,5.0,6.720981e+07,0.000000,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,5.0,6.737101e+07,0.000000,6.737101e+07,6.737101e+07,6.737101e+07,6.737101e+07,6.737101e+07
kayip,5.0,-1.611960e+05,0.000000,-1.611960e+05,-1.611960e+05,-1.611960e+05,-1.611960e+05,-1.611960e+05
kayip_orani,5.0,-2.398400e-01,0.000000,-2.398400e-01,-2.398400e-01,-2.398400e-01,-2.398400e-01,-2.398400e-01
type,5.0,2.000000e+00,0.000000,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00

In [8]:
type1=df[df["type"]==1]
type1.describe().T

,count,mean,std,min,25%,50%,75%,max
psnr,60.0,2.727383e+01,4.474266e+00,2.070984e+01,2.483371e+01,2.603108e+01,3.029971e+01,3.686237e+01
ssim_first,60.0,9.693535e-01,1.752648e-02,9.340840e-01,9.595702e-01,9.671470e-01,9.838823e-01,9.961280e-01
ssim_second,60.0,1.617663e+01,3.445419e+00,1.181012e+01,1.393304e+01,1.483422e+01,1.792784e+01,2.412077e+01
kaynak,60.0,6.720981e+07,0.000000e+00,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,60.0,6.349565e+07,3.311703e+06,5.845811e+07,6.003098e+07,6.370099e+07,6.710886e+07,6.737101e+07
kayip,60.0,3.714166e+06,3.311703e+06,-1.611960e+05,1.009480e+05,3.508820e+06,7.178836e+06,8.751700e+06
kayip_orani,60.0,5.526226e+00,4.927410e+00,-2.398400e-01,1.501983e-01,5.220696e+00,1.068123e+01,1.302146e+01
type,60.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [9]:
type1S10=df[df["server"]=="h10"]
type1S10.describe().T

,count,mean,std,min,25%,50%,75%,max
psnr,75.0,3.335378e+01,6.272100e+00,2.108702e+01,2.711868e+01,3.609705e+01,3.873418e+01,4.061864e+01
ssim_first,75.0,9.845574e-01,2.090525e-02,8.758290e-01,9.743255e-01,9.957820e-01,9.979670e-01,9.985750e-01
ssim_second,75.0,2.172483e+01,5.687961e+00,9.059810e+00,1.590565e+01,2.374891e+01,2.692458e+01,2.846119e+01
kaynak,75.0,6.720981e+07,0.000000e+00,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,75.0,6.581562e+07,2.730863e+06,5.924454e+07,6.566707e+07,6.737101e+07,6.737101e+07,6.737101e+07
kayip,75.0,1.394192e+06,2.730863e+06,-1.611960e+05,-1.611960e+05,-1.611960e+05,1.542740e+06,7.965268e+06
kayip_orani,75.0,2.074387e+00,4.063190e+00,-2.398400e-01,-2.398400e-01,-2.398400e-01,2.295409e+00,1.185135e+01
type,75.0,2.000000e+00,9.004503e-01,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00

In [10]:
type1S10=df[df["server"]=="h14"]
type1S10.describe().T

,count,mean,std,min,25%,50%,75%,max
psnr,75.0,3.296340e+01,6.523954e+00,2.070984e+01,2.609549e+01,3.375862e+01,3.955775e+01,4.071766e+01
ssim_first,75.0,9.840234e-01,1.878664e-02,9.340840e-01,9.675815e-01,9.948640e-01,9.984060e-01,9.986090e-01
ssim_second,75.0,2.157044e+01,5.893067e+00,1.181012e+01,1.489248e+01,2.289364e+01,2.797651e+01,2.856669e+01
kaynak,75.0,6.720981e+07,0.000000e+00,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,75.0,6.565833e+07,2.915080e+06,5.845811e+07,6.501171e+07,6.737101e+07,6.737101e+07,6.737101e+07
kayip,75.0,1.551478e+06,2.915080e+06,-1.611960e+05,-1.611960e+05,-1.611960e+05,2.198100e+06,8.751700e+06
kayip_orani,75.0,2.308410e+00,4.337283e+00,-2.398400e-01,-2.398400e-01,-2.398400e-01,3.270505e+00,1.302146e+01
type,75.0,2.000000e+00,9.004503e-01,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00

In [11]:
type1=df[df["type"]==2]
type1.describe().T

,count,mean,std,min,25%,50%,75%,max
psnr,30.0,3.490549e+01,4.923503,2.519239e+01,3.208798e+01,3.708678e+01,3.886050e+01,4.071199e+01
ssim_first,30.0,9.916816e-01,0.010296,9.661740e-01,9.923710e-01,9.961700e-01,9.978510e-01,9.986090e-01
ssim_second,30.0,2.331849e+01,4.497631,1.470745e+01,2.117695e+01,2.416794e+01,2.667829e+01,2.856669e+01
kaynak,30.0,6.720981e+07,0.000000,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,30.0,6.695158e+07,994290.003041,6.422528e+07,6.737101e+07,6.737101e+07,6.737101e+07,6.737101e+07
kayip,30.0,2.582344e+05,994290.003041,-1.611960e+05,-1.611960e+05,-1.611960e+05,-1.611960e+05,2.984532e+06
kayip_orani,30.0,3.842213e-01,1.479382,-2.398400e-01,-2.398400e-01,-2.398400e-01,-2.398400e-01,4.440619e+00
type,30.0,2.000000e+00,0.000000,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00